# Generated by Django 6.0.1 on 2026-02-03 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistoryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('genre', 'Genre'), ('artist', 'Artist'), ('album', 'Album'), ('track', 'Track')], max_length=20)),
                ('resource_id', models.IntegerField()),
                ('resource_name', models.CharField(max_length=500)),
                ('search_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engaged_resources', to='catalog.searchhistory')),
            ],
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-timestamp'], name='catalog_sea_user_id_9860e6_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistoryresource',
            index=models.Index(fields=['search_history', 'resource_type'], name='catalog_sea_search__12c1b0_idx'),
        ),
    ]
