# Generated by Django 6.0.3 on 2026-03-06 01:57
# Edited: 3-step pattern for unique callable-default fields
# (AddField null=True -> RunPython backfill -> AlterField null=False unique=True).
# See https://docs.djangoproject.com/en/6.0/howto/writing-migrations/#migrations-that-add-unique-fields

import uuid
import random
import time
from django.db import migrations, models


def _generate_juke_id():
    if hasattr(uuid, "uuid7"):
        return uuid.uuid7()
    now_ms = int(time.time() * 1000)
    raw = random.getrandbits(80)
    return uuid.UUID(
        fields=(
            now_ms & 0xFFFFFFFF,
            (now_ms >> 32) & 0xFFFF,
            ((now_ms >> 48) & 0x0FFF) | 0x7000,
            (raw >> 72) & 0x3F | 0x80,
            (raw >> 64) & 0xFF,
            raw & ((1 << 48) - 1),
        ),
    )


def _backfill_juke_ids(apps, schema_editor):
    for model_name in ('Genre', 'Artist', 'Album', 'Track'):
        Model = apps.get_model('catalog', model_name)
        for row in Model.objects.filter(juke_id__isnull=True).iterator():
            row.juke_id = _generate_juke_id()
            row.save(update_fields=['juke_id'])


def _reverse_noop(apps, schema_editor):
    # Reverse path: AlterField reversals re-allow null, RemoveField drops the column.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_searchhistory_searchhistoryresource_and_more'),
    ]

    operations = [
        # Step 1 — add juke_id nullable, no constraints yet.
        migrations.AddField(
            model_name='album',
            name='juke_id',
            field=models.UUIDField(default=_generate_juke_id, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='juke_id',
            field=models.UUIDField(default=_generate_juke_id, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='juke_id',
            field=models.UUIDField(default=_generate_juke_id, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='juke_id',
            field=models.UUIDField(default=_generate_juke_id, editable=False, null=True),
        ),
        # mbid — nullable, no backfill required.
        migrations.AddField(
            model_name='album',
            name='mbid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='mbid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='mbid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        # Step 2 — backfill per-row unique values.
        migrations.RunPython(_backfill_juke_ids, _reverse_noop),
        # Step 3 — tighten to null=False, unique=True.
        migrations.AlterField(
            model_name='album',
            name='juke_id',
            field=models.UUIDField(default=_generate_juke_id, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='juke_id',
            field=models.UUIDField(default=_generate_juke_id, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='juke_id',
            field=models.UUIDField(default=_generate_juke_id, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='juke_id',
            field=models.UUIDField(default=_generate_juke_id, editable=False, unique=True),
        ),
    ]
