# Generated by Django 6.0.3 on 2026-03-06 01:57
# Edited: 3-step pattern for unique callable-default fields
# (AddField null=True -> RunPython backfill -> AlterField null=False unique=True).
# See https://docs.djangoproject.com/en/6.0/howto/writing-migrations/#migrations-that-add-unique-fields

import uuid
from django.db import migrations, models


def _backfill_juke_ids(apps, schema_editor):
    for model_name in ('Genre', 'Artist', 'Album', 'Track'):
        Model = apps.get_model('catalog', model_name)
        for row in Model.objects.filter(juke_id__isnull=True).iterator():
            row.juke_id = uuid.uuid7()
            row.save(update_fields=['juke_id'])


def _reverse_noop(apps, schema_editor):
    # Reverse path: AlterField reversals re-allow null, RemoveField drops the column.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_searchhistory_searchhistoryresource_and_more'),
    ]

    operations = [
        # Step 1 — add juke_id nullable, no constraints yet.
        migrations.AddField(
            model_name='album',
            name='juke_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='juke_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='juke_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='juke_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, null=True),
        ),
        # mbid — nullable, no backfill required.
        migrations.AddField(
            model_name='album',
            name='mbid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='mbid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='mbid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        # Step 2 — backfill per-row unique values.
        migrations.RunPython(_backfill_juke_ids, _reverse_noop),
        # Step 3 — tighten to null=False, unique=True.
        migrations.AlterField(
            model_name='album',
            name='juke_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='juke_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='juke_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='juke_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, unique=True),
        ),
    ]
