# Generated by Django 6.0.3 on 2026-03-06 02:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_album_juke_id_album_mbid_artist_juke_id_artist_mbid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumExternalIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('youtube_music', 'YouTube Music'), ('musicbrainz', 'MusicBrainz')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='catalog.album', to_field='juke_id')),
            ],
            options={
                'db_table': 'catalog_album_external_id',
                'abstract': False,
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ArtistExternalIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('youtube_music', 'YouTube Music'), ('musicbrainz', 'MusicBrainz')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='catalog.artist', to_field='juke_id')),
            ],
            options={
                'db_table': 'catalog_artist_external_id',
                'abstract': False,
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='GenreExternalIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('youtube_music', 'YouTube Music'), ('musicbrainz', 'MusicBrainz')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='catalog.genre', to_field='juke_id')),
            ],
            options={
                'db_table': 'catalog_genre_external_id',
                'abstract': False,
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='TrackExternalIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('youtube_music', 'YouTube Music'), ('musicbrainz', 'MusicBrainz')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='catalog.track', to_field='juke_id')),
            ],
            options={
                'db_table': 'catalog_track_external_id',
                'abstract': False,
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
