# Generated by Django 6.0.2 on 2026-03-14 14:29

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_albumexternalidentifier_artistexternalidentifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='juke_id',
            field=models.UUIDField(default=catalog.models._generate_juke_id, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='juke_id',
            field=models.UUIDField(default=catalog.models._generate_juke_id, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='juke_id',
            field=models.UUIDField(default=catalog.models._generate_juke_id, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='juke_id',
            field=models.UUIDField(default=catalog.models._generate_juke_id, editable=False, unique=True),
        ),
    ]
