# Generated by Django 6.1.1 on 2026-10-01 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('frequency', models.DecimalField(decimal_places=1, max_digits=4)),
                ('seeds', models.JSONField(blank=True, default=list)),
                ('feelings', models.JSONField(blank=True, default=list)),
                ('learning', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['frequency', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=64)),
                ('spotify_artist_id', models.CharField(blank=True, default='', max_length=64)),
                ('event', models.CharField(choices=[('play', 'play'), ('complete', 'complete'), ('skip', 'skip'), ('less', 'less'), ('not_on_station', 'not_on_station'), ('never_artist', 'never_artist'), ('seek', 'seek'), ('save', 'save'), ('recognized', 'recognized'), ('queued', 'queued')], max_length=24)),
                ('position_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_events', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='radio.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('station', 'This station'), ('everywhere', 'Everywhere')], max_length=16)),
                ('kind', models.CharField(choices=[('track', 'Track'), ('artist', 'Artist'), ('genre', 'Genre'), ('text', 'Text')], max_length=16)),
                ('value', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_exclusions', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='radio.station')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=64)),
                ('reactions', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='radio.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['user', 'kind'], name='radio_station_user_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'personal')), fields=('user',), name='radio_station_one_personal_per_user'),
        ),
        migrations.AddIndex(
            model_name='listeningevent',
            index=models.Index(fields=['user', '-created_at'], name='radio_event_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningevent',
            index=models.Index(fields=['user', 'event', '-created_at'], name='radio_event_user_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='exclusion',
            index=models.Index(fields=['user', 'station'], name='radio_exclusion_user_stn_idx'),
        ),
        migrations.AddIndex(
            model_name='trackreaction',
            index=models.Index(fields=['user', '-updated_at'], name='radio_reaction_user_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackreaction',
            constraint=models.UniqueConstraint(fields=('user', 'spotify_track_id'), name='radio_reaction_user_track_uniq'),
        ),
    ]
