# Generated by Django 6.1.1 on 2026-10-01 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', True)), fields=('user', 'scope', 'kind', 'value'), name='radio_exclusion_everywhere_uniq'),
        ),
        migrations.AddConstraint(
            model_name='exclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', False)), fields=('user', 'station', 'kind', 'value'), name='radio_exclusion_station_uniq'),
        ),
    ]
