# Generated by Django 6.0.3 on 2026-03-06 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_albumexternalidentifier_artistexternalidentifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('track_path', models.CharField(max_length=1024)),
                ('license', models.CharField(max_length=128)),
                ('license_url', models.URLField(blank=True, max_length=512, null=True)),
                ('allowed_envs', models.CharField(choices=[('production', 'Production'), ('research', 'Research'), ('both', 'Both')], max_length=16)),
                ('checksum', models.CharField(max_length=128)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('mbid_candidate', models.UUIDField(blank=True, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=256, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corpus_manifest_entries', to='catalog.track', to_field='juke_id')),
            ],
            options={
                'db_table': 'mlcore_corpus_manifest',
                'indexes': [models.Index(fields=['source'], name='mlcore_corp_source_dc646b_idx'), models.Index(fields=['allowed_envs'], name='mlcore_corp_allowed_b12ad2_idx')],
                'unique_together': {('source', 'track_path', 'checksum')},
            },
        ),
    ]
