# Generated by Django 6.0.3 on 2026-03-06 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCoOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_a_juke_id', models.UUIDField()),
                ('item_b_juke_id', models.UUIDField()),
                ('co_count', models.IntegerField()),
                ('pmi_score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mlcore_item_cooccurrence',
                'indexes': [models.Index(fields=['item_a_juke_id'], name='mlcore_item_item_a__bfbfe3_idx'), models.Index(fields=['item_b_juke_id'], name='mlcore_item_item_b__baff90_idx')],
                'unique_together': {('item_a_juke_id', 'item_b_juke_id')},
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('candidate_label', models.CharField(db_index=True, max_length=64)),
                ('metric_name', models.CharField(max_length=64)),
                ('metric_value', models.FloatField()),
                ('dataset_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mlcore_model_evaluation',
                'indexes': [models.Index(fields=['candidate_label', 'dataset_hash', 'metric_name'], name='mlcore_mode_candida_65e94f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_id', models.UUIDField(blank=True, null=True)),
                ('candidate_label', models.CharField(max_length=64)),
                ('baseline_label', models.CharField(max_length=64)),
                ('dataset_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=16)),
                ('gate_results', models.JSONField(default=dict)),
                ('block_reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mlcore_model_promotion',
                'ordering': ['-created_at'],
            },
        ),
    ]
