# Generated by manual update for mlcore cooccurrence training provenance.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0002_itemcooccurrence_modelevaluation_modelpromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ranker_label', models.CharField(max_length=64)),
                ('training_hash', models.CharField(max_length=64, db_index=True)),
                ('baskets_processed', models.IntegerField()),
                ('baskets_skipped', models.IntegerField()),
                ('items_seen', models.IntegerField()),
                ('pairs_written', models.IntegerField()),
                ('source_row_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mlcore_training_run',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['ranker_label']),
                    models.Index(fields=['training_hash']),
                    models.Index(fields=['created_at']),
                ],
            },
        ),
        migrations.AddField(
            model_name='itemcooccurrence',
            name='training_run',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cooccurrence_rows',
                to='mlcore.trainingrun',
            ),
        ),
        migrations.AddIndex(
            model_name='itemcooccurrence',
            index=models.Index(fields=['training_run']),
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='training_run',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='evaluations',
                to='mlcore.trainingrun',
            ),
        ),
    ]
