# Generated by manual update for MLCore ListenBrainz ingestion.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_albumexternalidentifier_artistexternalidentifier_and_more'),
        ('mlcore', '0003_mlcore_trainingrun_lineage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceIngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('import_mode', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], max_length=16)),
                ('source_version', models.CharField(max_length=255)),
                ('raw_path', models.CharField(max_length=1024)),
                ('checksum', models.CharField(max_length=128)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('running', 'Running'),
                        ('succeeded', 'Succeeded'),
                        ('failed', 'Failed'),
                        ('skipped', 'Skipped'),
                    ],
                    default='pending',
                    max_length=16,
                )),
                ('source_row_count', models.IntegerField(default=0)),
                ('imported_row_count', models.IntegerField(default=0)),
                ('duplicate_row_count', models.IntegerField(default=0)),
                ('canonicalized_row_count', models.IntegerField(default=0)),
                ('unresolved_row_count', models.IntegerField(default=0)),
                ('malformed_row_count', models.IntegerField(default=0)),
                ('policy_classification', models.CharField(blank=True, default='', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mlcore_source_ingestion_run',
                'ordering': ['-started_at'],
                'indexes': [
                    models.Index(fields=['source', 'import_mode'], name='mlcore_src_source_6e8952_idx'),
                    models.Index(fields=['source', 'source_version'], name='mlcore_src_source_b153c1_idx'),
                    models.Index(fields=['status'], name='mlcore_src_status_932106_idx'),
                    models.Index(fields=['started_at'], name='mlcore_src_started_7c3252_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ListenBrainzRawListen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_event_signature', models.CharField(max_length=64, unique=True)),
                ('source_user_id', models.CharField(db_index=True, max_length=64)),
                ('played_at', models.DateTimeField(db_index=True)),
                ('recording_mbid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('release_mbid', models.UUIDField(blank=True, null=True)),
                ('recording_msid', models.CharField(blank=True, default='', max_length=255)),
                ('release_msid', models.CharField(blank=True, default='', max_length=255)),
                ('track_name', models.CharField(blank=True, default='', max_length=1024)),
                ('artist_name', models.CharField(blank=True, default='', max_length=1024)),
                ('release_name', models.CharField(blank=True, default='', max_length=1024)),
                ('track_identifier_candidates', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listenbrainz_raw_rows', to='mlcore.sourceingestionrun')),
            ],
            options={
                'db_table': 'mlcore_listenbrainz_raw_listen',
                'ordering': ['played_at', 'id'],
                'indexes': [
                    models.Index(fields=['import_run'], name='mlcore_lis_import__6c1e6e_idx'),
                    models.Index(fields=['source_user_id', 'played_at'], name='mlcore_lis_source__5069fc_idx'),
                    models.Index(fields=['recording_mbid'], name='mlcore_lis_recordi_534bf5_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='NormalizedInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('source_version', models.CharField(db_index=True, max_length=255)),
                ('source_event_signature', models.CharField(max_length=64, unique=True)),
                ('source_user_id', models.CharField(db_index=True, max_length=64)),
                ('played_at', models.DateTimeField(db_index=True)),
                ('session_hint', models.CharField(db_index=True, max_length=128)),
                ('track_identifier_candidates', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_interactions', to='mlcore.sourceingestionrun')),
                ('raw_listen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_interaction', to='mlcore.listenbrainzrawlisten')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_interactions', to='catalog.track', to_field='juke_id')),
            ],
            options={
                'db_table': 'mlcore_normalized_interaction',
                'ordering': ['played_at', 'id'],
                'indexes': [
                    models.Index(fields=['source_id', 'source_version'], name='mlcore_nor_source__54a8d9_idx'),
                    models.Index(fields=['source_user_id', 'played_at'], name='mlcore_nor_source__09767c_idx'),
                    models.Index(fields=['track'], name='mlcore_nor_track_i_2555db_idx'),
                    models.Index(fields=['import_run'], name='mlcore_nor_import__0fa0e0_idx'),
                ],
            },
        ),
    ]
