# Generated by manual update for oversized ListenBrainz metadata values.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0004_mlcore_listenbrainz_ingestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenbrainzrawlisten',
            name='artist_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='listenbrainzrawlisten',
            name='recording_msid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='listenbrainzrawlisten',
            name='release_msid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='listenbrainzrawlisten',
            name='release_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='listenbrainzrawlisten',
            name='track_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
