# Generated by Django 6.0.3 on 2026-04-12 11:56

import django.db.models.deletion
from django.db import migrations, models


def backfill_listenbrainz_fingerprints(apps, schema_editor):
    SourceIngestionRun = apps.get_model('mlcore', 'SourceIngestionRun')
    for run in SourceIngestionRun.objects.filter(source='listenbrainz').exclude(checksum=''):
        metadata = run.metadata or {}
        if metadata.get('checksum_mode') != 'stat_fingerprint':
            continue
        if run.fingerprint:
            continue
        run.fingerprint = run.checksum
        run.checksum = ''
        metadata.pop('checksum_mode', None)
        metadata['fingerprint_mode'] = 'stat_fingerprint'
        run.metadata = metadata
        run.save(update_fields=['fingerprint', 'checksum', 'metadata'])


def restore_listenbrainz_checksums(apps, schema_editor):
    SourceIngestionRun = apps.get_model('mlcore', 'SourceIngestionRun')
    for run in SourceIngestionRun.objects.filter(source='listenbrainz').exclude(fingerprint=''):
        metadata = run.metadata or {}
        if metadata.get('fingerprint_mode') != 'stat_fingerprint':
            continue
        if run.checksum:
            continue
        run.checksum = run.fingerprint
        run.fingerprint = ''
        metadata.pop('fingerprint_mode', None)
        metadata['checksum_mode'] = 'stat_fingerprint'
        run.metadata = metadata
        run.save(update_fields=['fingerprint', 'checksum', 'metadata'])


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0009_reapply_mlcore_tablespace_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceingestionrun',
            name='fingerprint',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='listenbrainzsessiontrack',
            name='import_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listenbrainz_session_tracks', to='mlcore.sourceingestionrun'),
        ),
        migrations.RunPython(
            backfill_listenbrainz_fingerprints,
            restore_listenbrainz_checksums,
        ),
    ]
