# Generated by Django 6.0.3 on 2026-04-13 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0010_sourceingestionrun_fingerprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullIngestionLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64, unique=True)),
                ('holder_type', models.CharField(default='full_ingestion', max_length=32)),
                ('holder_run_id', models.CharField(blank=True, default='', max_length=64)),
                ('source_version', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField(auto_now=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mlcore_full_ingestion_lease',
                'ordering': ['provider'],
                'indexes': [models.Index(fields=['status'], name='mlcore_fil_status_c3a27d_idx'), models.Index(fields=['heartbeat_at'], name='mlcore_fil_heartbe_207655_idx')],
            },
        ),
    ]
