# Generated by Django 6.0.3 on 2026-04-27 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0015_trim_cooccurrence_training_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOccurrenceTrainingBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('algorithm_version', models.CharField(max_length=64)),
                ('bucket_count', models.IntegerField()),
                ('bucket_index', models.IntegerField()),
                ('session_key', models.BinaryField(max_length=32)),
                ('item_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_training_baskets', to='mlcore.trainingrun')),
            ],
            options={
                'db_table': 'mlcore_cooccurrence_training_basket',
                'indexes': [models.Index(fields=['training_run', 'bucket_index'], name='mlcore_ctbs_run_bucket_idx'), models.Index(fields=['training_run', 'session_key'], name='mlcore_ctbs_run_session_idx'), models.Index(fields=['source', 'algorithm_version'], name='mlcore_ctbs_src_alg_idx')],
                'unique_together': {('training_run', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='CoOccurrenceTrainingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_count', models.IntegerField()),
                ('bucket_index', models.IntegerField()),
                ('item_a_juke_id', models.UUIDField()),
                ('item_b_juke_id', models.UUIDField()),
                ('co_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_training_pairs', to='mlcore.trainingrun')),
            ],
            options={
                'db_table': 'mlcore_cooccurrence_training_pair',
                'indexes': [models.Index(fields=['training_run', 'bucket_index'], name='mlcore_ctp_run_bucket_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoOccurrenceTrainingSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_count', models.IntegerField()),
                ('bucket_index', models.IntegerField()),
                ('session_key', models.BinaryField(max_length=32)),
                ('item_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_training_session_items', to='mlcore.trainingrun')),
            ],
            options={
                'db_table': 'mlcore_cooccurrence_training_session_item',
                'indexes': [models.Index(fields=['training_run', 'bucket_index', 'session_key'], name='mlcore_ctsi_run_bkt_sess_idx'), models.Index(fields=['training_run', 'item_id'], name='mlcore_ctsi_run_item_idx')],
                'unique_together': {('training_run', 'session_key', 'item_id')},
            },
        ),
    ]
