# Generated by Django 6.0.3 on 2026-04-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0016_cooccurrence_training_staging'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cooccurrencetrainingbasket',
            name='mlcore_ctbs_run_bucket_idx',
        ),
        migrations.RemoveIndex(
            model_name='cooccurrencetrainingbasket',
            name='mlcore_ctbs_src_alg_idx',
        ),
        migrations.RemoveIndex(
            model_name='cooccurrencetrainingsessionitem',
            name='mlcore_ctsi_run_item_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cooccurrencetrainingbasket',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cooccurrencetrainingsessionitem',
            unique_together=set(),
        ),
    ]
