# Generated by Django 6.0.3 on 2026-04-27 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0017_trim_cooccurrence_staging_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooccurrencetrainingbasket',
            name='training_run',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_training_baskets', to='mlcore.trainingrun'),
        ),
        migrations.AlterField(
            model_name='cooccurrencetrainingpair',
            name='training_run',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_training_pairs', to='mlcore.trainingrun'),
        ),
        migrations.AlterField(
            model_name='cooccurrencetrainingsessionitem',
            name='training_run',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_training_session_items', to='mlcore.trainingrun'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE mlcore_cooccurrence_training_basket
                    SET (autovacuum_enabled = false, toast.autovacuum_enabled = false);
                ALTER TABLE mlcore_cooccurrence_training_session_item
                    SET (autovacuum_enabled = false, toast.autovacuum_enabled = false);
                ALTER TABLE mlcore_cooccurrence_training_pair
                    SET (autovacuum_enabled = false, toast.autovacuum_enabled = false);
            """,
            reverse_sql="""
                ALTER TABLE mlcore_cooccurrence_training_basket
                    RESET (autovacuum_enabled, toast.autovacuum_enabled);
                ALTER TABLE mlcore_cooccurrence_training_session_item
                    RESET (autovacuum_enabled, toast.autovacuum_enabled);
                ALTER TABLE mlcore_cooccurrence_training_pair
                    RESET (autovacuum_enabled, toast.autovacuum_enabled);
            """,
        ),
    ]
