# Generated by Codex on 2026-05-30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0018_trim_cooccurrence_staging_fk_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalItemAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=512)),
                ('confidence', models.FloatField(default=1.0)),
                ('source_version', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('conflict', 'Conflict')], default='active', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='mlcore.canonicalitem')),
            ],
            options={
                'db_table': 'mlcore_canonical_item_alias',
                'ordering': ['source', 'resource_type', 'source_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='canonicalitemalias',
            constraint=models.UniqueConstraint(fields=('source', 'resource_type', 'source_id'), name='mlcore_cia_source_resource_source_id_uniq'),
        ),
        migrations.AddIndex(
            model_name='canonicalitemalias',
            index=models.Index(fields=['canonical_item'], name='mlcore_cia_canonic_7d4fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalitemalias',
            index=models.Index(fields=['source', 'resource_type', 'source_id'], name='mlcore_cia_lookup_117b92_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalitemalias',
            index=models.Index(fields=['status'], name='mlcore_cia_status_6e75d3_idx'),
        ),
    ]
