# Generated by Django 6.0.3 on 2026-06-13 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0026_canonical_identity_hot_tablespace'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalAliasMaterializationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_version', models.CharField(blank=True, default='', max_length=255)),
                ('algorithm_version', models.CharField(default='canonical-alias-v2', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('current_phase', models.CharField(blank=True, default='', max_length=64)),
                ('include_catalog_tracks', models.BooleanField(default=False)),
                ('batch_size', models.IntegerField(default=100000)),
                ('total_items', models.BigIntegerField(default=0)),
                ('processed_items', models.BigIntegerField(default=0)),
                ('created_count', models.BigIntegerField(default=0)),
                ('existing_count', models.BigIntegerField(default=0)),
                ('conflict_count', models.BigIntegerField(default=0)),
                ('batches_processed', models.BigIntegerField(default=0)),
                ('checkpoints', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mlcore_canonical_alias_materialization_run',
                'ordering': ['-started_at'],
                'db_tablespace': 'juke_mlcore_hot',
                'indexes': [models.Index(fields=['status'], name='mlcore_camr_status_idx'), models.Index(fields=['source_version'], name='mlcore_camr_source_idx'), models.Index(fields=['started_at'], name='mlcore_camr_started_idx')],
            },
        ),
    ]
