# Generated by Django 6.0.3 on 2026-06-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0027_canonical_alias_materialization_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBrainzRecordingISRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_mbid', models.UUIDField()),
                ('isrc', models.CharField(max_length=12)),
                ('source_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mlcore_musicbrainz_recording_isrc',
                'ordering': ['recording_mbid', 'isrc'],
                'db_tablespace': 'juke_mlcore_cold',
                'indexes': [models.Index(fields=['recording_mbid'], name='mlcore_mbri_mbid_idx'), models.Index(fields=['isrc'], name='mlcore_mbri_isrc_idx'), models.Index(fields=['source_version'], name='mlcore_mbri_source_idx')],
                'unique_together': {('recording_mbid', 'isrc', 'source_version')},
            },
        ),
        migrations.CreateModel(
            name='MusicBrainzRecordingURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_mbid', models.UUIDField()),
                ('url', models.TextField()),
                ('url_fingerprint', models.CharField(max_length=32)),
                ('provider', models.CharField(blank=True, default='other', max_length=32)),
                ('link_type_id', models.BigIntegerField()),
                ('link_type_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mlcore_musicbrainz_recording_url',
                'ordering': ['recording_mbid', 'provider', 'url'],
                'db_tablespace': 'juke_mlcore_cold',
                'indexes': [models.Index(fields=['recording_mbid'], name='mlcore_mbru_mbid_idx'), models.Index(fields=['provider'], name='mlcore_mbru_provider_idx'), models.Index(fields=['source_version'], name='mlcore_mbru_source_idx')],
                'unique_together': {('recording_mbid', 'url_fingerprint', 'source_version')},
            },
        ),
        migrations.RunSQL(
            sql='''
                CREATE UNLOGGED TABLE mlcore_mb_recording_stage (
                    recording_id bigint PRIMARY KEY,
                    recording_mbid uuid NOT NULL
                ) TABLESPACE juke_mlcore_cold;
                CREATE UNLOGGED TABLE mlcore_mb_isrc_stage (
                    recording_id bigint NOT NULL,
                    isrc varchar(12) NOT NULL
                ) TABLESPACE juke_mlcore_cold;
                CREATE INDEX mlcore_mb_isrc_stage_recording_idx
                    ON mlcore_mb_isrc_stage (recording_id)
                    TABLESPACE juke_mlcore_cold;
                CREATE UNLOGGED TABLE mlcore_mb_url_stage (
                    url_id bigint PRIMARY KEY,
                    url text NOT NULL
                ) TABLESPACE juke_mlcore_cold;
                CREATE UNLOGGED TABLE mlcore_mb_recording_url_stage (
                    link_id bigint NOT NULL,
                    recording_id bigint NOT NULL,
                    url_id bigint NOT NULL
                ) TABLESPACE juke_mlcore_cold;
                CREATE INDEX mlcore_mb_recording_url_stage_recording_idx
                    ON mlcore_mb_recording_url_stage (recording_id)
                    TABLESPACE juke_mlcore_cold;
                CREATE INDEX mlcore_mb_recording_url_stage_url_idx
                    ON mlcore_mb_recording_url_stage (url_id)
                    TABLESPACE juke_mlcore_cold;
                CREATE INDEX mlcore_mb_recording_url_stage_link_idx
                    ON mlcore_mb_recording_url_stage (link_id)
                    TABLESPACE juke_mlcore_cold;
                CREATE UNLOGGED TABLE mlcore_mb_link_stage (
                    link_id bigint PRIMARY KEY,
                    link_type_id bigint NOT NULL
                ) TABLESPACE juke_mlcore_cold;
                CREATE UNLOGGED TABLE mlcore_mb_link_type_stage (
                    link_type_id bigint PRIMARY KEY,
                    entity_type0 varchar(50) NOT NULL,
                    entity_type1 varchar(50) NOT NULL,
                    name varchar(255) NOT NULL
                ) TABLESPACE juke_mlcore_cold;
            ''',
            reverse_sql='''
                DROP TABLE IF EXISTS mlcore_mb_link_type_stage;
                DROP TABLE IF EXISTS mlcore_mb_link_stage;
                DROP TABLE IF EXISTS mlcore_mb_recording_url_stage;
                DROP TABLE IF EXISTS mlcore_mb_url_stage;
                DROP TABLE IF EXISTS mlcore_mb_isrc_stage;
                DROP TABLE IF EXISTS mlcore_mb_recording_stage;
            ''',
        ),
    ]
