# Generated by Django 6.0.3 on 2026-06-15 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0028_musicbrainzrecordingisrc_musicbrainzrecordingurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenBrainzIdentityShard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_version', models.CharField(max_length=255)),
                ('shard_key', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(max_length=64)),
                ('output_path', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('source_row_count', models.BigIntegerField(default=0)),
                ('mapped_row_count', models.BigIntegerField(default=0)),
                ('unique_pair_count', models.BigIntegerField(default=0)),
                ('malformed_row_count', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'mlcore_listenbrainz_identity_shard',
                'ordering': ['source_version', 'shard_key'],
                'db_tablespace': 'juke_mlcore_cold',
                'indexes': [models.Index(fields=['source_version', 'status'], name='mlcore_lbis_version_status_idx')],
                'unique_together': {('source_version', 'shard_key')},
            },
        ),
        migrations.CreateModel(
            name='ListenBrainzMSIDMBIDMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_msid', models.UUIDField()),
                ('recording_mbid', models.UUIDField()),
                ('source_version', models.CharField(max_length=255)),
                ('shard_observation_count', models.BigIntegerField(default=1)),
                ('first_shard', models.CharField(max_length=255)),
                ('last_shard', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('conflict', 'Conflict'), ('retired', 'Retired')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mlcore_listenbrainz_msid_mbid_mapping',
                'db_tablespace': 'juke_mlcore_cold',
                'indexes': [models.Index(fields=['recording_msid'], name='mlcore_lbmm_msid_idx'), models.Index(fields=['recording_mbid'], name='mlcore_lbmm_mbid_idx'), models.Index(fields=['source_version', 'status'], name='mlcore_lbmm_version_status_idx')],
                'unique_together': {('recording_msid', 'recording_mbid', 'source_version')},
            },
        ),
        migrations.CreateModel(
            name='CanonicalItemRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(default='same_recording', max_length=32)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(max_length=64)),
                ('source_version', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('conflict', 'Conflict'), ('retired', 'Retired')], default='active', max_length=16)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_canonical_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_redirect', to='mlcore.canonicalitem')),
                ('to_canonical_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_redirects', to='mlcore.canonicalitem')),
            ],
            options={
                'db_table': 'mlcore_canonical_item_redirect',
                'db_tablespace': 'juke_mlcore_hot',
                'indexes': [models.Index(fields=['to_canonical_item'], name='mlcore_cir_target_idx'), models.Index(fields=['status'], name='mlcore_cir_status_idx'), models.Index(fields=['source', 'source_version'], name='mlcore_cir_source_version_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_canonical_item', models.F('to_canonical_item')), _negated=True), name='mlcore_cir_no_self_redirect')],
            },
        ),
        migrations.RunSQL(
            sql='''
                CREATE UNLOGGED TABLE mlcore_listenbrainz_identity_pair_stage (
                    recording_msid uuid NOT NULL,
                    recording_mbid uuid NOT NULL
                ) TABLESPACE juke_mlcore_cold;
                CREATE INDEX mlcore_lb_identity_pair_stage_msid_idx
                    ON mlcore_listenbrainz_identity_pair_stage (recording_msid)
                    TABLESPACE juke_mlcore_cold;
            ''',
            reverse_sql='DROP TABLE IF EXISTS mlcore_listenbrainz_identity_pair_stage;',
        ),
    ]
