# Generated by Django 6.0.3 on 2026-06-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0029_listenbrainzidentityshard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceingestionrun',
            name='canonicalized_row_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sourceingestionrun',
            name='duplicate_row_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sourceingestionrun',
            name='imported_row_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sourceingestionrun',
            name='malformed_row_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sourceingestionrun',
            name='source_row_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sourceingestionrun',
            name='unresolved_row_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
