# Generated by Django 6.0.3 on 2026-06-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0030_alter_sourceingestionrun_canonicalized_row_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenBrainzMSIDMBIDConflictResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_msid', models.UUIDField()),
                ('chosen_recording_mbid', models.UUIDField()),
                ('source_version', models.CharField(max_length=255)),
                ('policy_version', models.CharField(max_length=64)),
                ('winner_shard_observation_count', models.BigIntegerField(default=0)),
                ('total_shard_observation_count', models.BigIntegerField(default=0)),
                ('candidate_count', models.IntegerField(default=0)),
                ('winner_share', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('conflict', 'Conflict'), ('retired', 'Retired')], default='active', max_length=16)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mlcore_listenbrainz_msid_mbid_conflict_resolution',
                'ordering': ['source_version', 'recording_msid'],
                'db_tablespace': 'juke_mlcore_cold',
                'indexes': [models.Index(fields=['source_version', 'policy_version', 'status'], name='mlcore_lbmcr_policy_status_idx'), models.Index(fields=['chosen_recording_mbid'], name='mlcore_lbmcr_mbid_idx')],
                'unique_together': {('recording_msid', 'source_version', 'policy_version')},
            },
        ),
    ]
