# Generated by Django 6.0.3 on 2026-06-22 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcore', '0032_listenbrainz_isrc_extraction_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderHydrationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=16)),
                ('requested_limit', models.BigIntegerField(blank=True, null=True)),
                ('attempted_count', models.BigIntegerField(default=0)),
                ('matched_count', models.BigIntegerField(default=0)),
                ('no_match_count', models.BigIntegerField(default=0)),
                ('ambiguous_count', models.BigIntegerField(default=0)),
                ('retry_count', models.BigIntegerField(default=0)),
                ('rate_limited_count', models.BigIntegerField(default=0)),
                ('dead_count', models.BigIntegerField(default=0)),
                ('request_count', models.BigIntegerField(default=0)),
                ('configured_rps', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mlcore_provider_hydration_run',
                'ordering': ['-started_at'],
                'db_tablespace': 'juke_mlcore_cold',
                'indexes': [models.Index(fields=['provider', 'started_at'], name='mlcore_phr_prov_start_idx'), models.Index(fields=['status'], name='mlcore_phr_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderHydrationItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('identifier_type', models.CharField(max_length=32)),
                ('identifier', models.CharField(max_length=512)),
                ('priority', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retry', 'Retry'), ('matched', 'Matched'), ('no_match', 'No match'), ('ambiguous', 'Ambiguous'), ('dead', 'Dead')], default='pending', max_length=16)),
                ('attempt_count', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('leased_by', models.CharField(blank=True, default='', max_length=128)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_http_status', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('source_version', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydration_items', to='mlcore.canonicalitem')),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='mlcore.providerhydrationrun')),
            ],
            options={
                'db_table': 'mlcore_provider_hydration_item',
                'ordering': ['priority', 'id'],
                'db_tablespace': 'juke_mlcore_cold',
                'indexes': [models.Index(fields=['provider', 'status', 'next_attempt_at', 'priority'], name='mlcore_phi_claim_idx'), models.Index(fields=['canonical_item', 'provider'], name='mlcore_phi_canon_prov_idx'), models.Index(fields=['lease_expires_at'], name='mlcore_phi_lease_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'identifier_type', 'identifier'), name='mlcore_phi_provider_identifier_uniq')],
            },
        ),
    ]
