# Generated by Django 6.1.1 on 2026-09-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0002_music_memories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorytag',
            name='normalized',
            field=models.CharField(max_length=180),
        ),
    ]
