#!/usr/bin/env bash
# scripts/setup_cli.sh — first-time setup for the Juke CLI (juked + juke).
#
# What this does:
#   1. Verifies Go 1.24+ is available (suggests brew install go on macOS).
#   2. Reads BACKEND_URL from the repo's .env (falls back to http://localhost:8000).
#   3. Creates the platform config directory and writes config.toml.
#   4. Builds juked and juke into cli/dist/.
#   5. Optionally symlinks the binaries to ~/bin (or wherever the user prefers).
#   6. Prints a "what to do next" summary.
#
# Usage:
#   ./scripts/setup_cli.sh           # interactive
#   BACKEND_URL=https://... ./scripts/setup_cli.sh   # override backend URL
#   NO_SYMLINK=1 ./scripts/setup_cli.sh              # skip ~/bin symlinks
#
# Re-running is safe: the config file is only written if it does not already
# exist, and binaries are always rebuilt.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLI_DIR="$REPO_ROOT/cli"
DIST_DIR="$CLI_DIR/dist"

# ── colours ───────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  BOLD='\033[1m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; RESET='\033[0m'
else
  BOLD=''; GREEN=''; YELLOW=''; RED=''; RESET=''
fi

step()  { echo -e "${BOLD}==> $*${RESET}"; }
ok()    { echo -e "  ${GREEN}✓${RESET} $*"; }
warn()  { echo -e "  ${YELLOW}!${RESET} $*"; }
fail()  { echo -e "  ${RED}✗${RESET} $*"; exit 1; }

# ── 1. Check Go ───────────────────────────────────────────────────────────────
step "Checking Go installation"

if ! command -v go &>/dev/null; then
  if [[ "$(uname)" == "Darwin" ]] && command -v brew &>/dev/null; then
    warn "Go not found. Installing via Homebrew…"
    brew install go
  else
    fail "Go is not installed. Install it from https://go.dev/dl/ and re-run this script."
  fi
fi

GO_VERSION="$(go version | awk '{print $3}' | sed 's/go//')"
GO_MAJOR="${GO_VERSION%%.*}"
GO_MINOR="${GO_VERSION#*.}"; GO_MINOR="${GO_MINOR%%.*}"

if (( GO_MAJOR < 1 || ( GO_MAJOR == 1 && GO_MINOR < 24 ) )); then
  fail "Go $GO_VERSION is too old. Need 1.24+. Run: brew upgrade go"
fi
ok "Go $GO_VERSION"

# ── 2. Resolve BACKEND_URL ────────────────────────────────────────────────────
step "Resolving backend URL"

# Allow explicit env override, then fall back to .env, then default.
if [[ -z "${BACKEND_URL:-}" ]]; then
  ENV_FILE="$REPO_ROOT/.env"
  if [[ -f "$ENV_FILE" ]]; then
    # Source only the BACKEND_URL line to avoid polluting the environment.
    BACKEND_URL="$(grep -E '^BACKEND_URL=' "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'")"
  fi
fi
BACKEND_URL="${BACKEND_URL:-http://localhost:8000}"
ok "backend_url = $BACKEND_URL"

# ── 3. Write config.toml ──────────────────────────────────────────────────────
step "Writing CLI config"

case "$(uname -s)" in
  Darwin)
    CONFIG_DIR="$HOME/Library/Application Support/Juke"
    ;;
  Linux)
    CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/juke"
    ;;
  MINGW*|MSYS*|CYGWIN*)
    CONFIG_DIR="${APPDATA:-$HOME/AppData/Roaming}/Juke"
    ;;
  *)
    CONFIG_DIR="$HOME/.config/juke"
    ;;
esac

CONFIG_FILE="$CONFIG_DIR/config.toml"
mkdir -p "$CONFIG_DIR"

if [[ -f "$CONFIG_FILE" ]]; then
  warn "Config already exists at: $CONFIG_FILE"
  warn "Not overwriting. Delete it and re-run to regenerate."
else
  cat > "$CONFIG_FILE" << TOML
# Juke CLI configuration
# Generated by scripts/setup_cli.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit this file to change settings; restart juked for changes to take effect.

# The base URL of the Juke backend (no trailing slash).
backend_url = "$BACKEND_URL"

[transport]
# "auto" tries WebSocket first, falls back to polling.
# "polling" forces the polling path (useful if WebSocket is blocked).
mode = "auto"
poll_interval_seconds = 10
TOML
  ok "Created $CONFIG_FILE"
fi

# ── 4. Build binaries ─────────────────────────────────────────────────────────
step "Building juked and juke"

mkdir -p "$DIST_DIR"
cd "$CLI_DIR"

CGO_ENABLED=0 go build -o "$DIST_DIR/juked" ./cmd/juked
CGO_ENABLED=0 go build -o "$DIST_DIR/juke"  ./cmd/juke
ok "Built $DIST_DIR/juked"
ok "Built $DIST_DIR/juke"

# ── 5. Symlink to ~/bin ───────────────────────────────────────────────────────
if [[ "${NO_SYMLINK:-0}" != "1" ]]; then
  step "Installing to ~/bin"
  mkdir -p "$HOME/bin"

  for bin in juked juke; do
    TARGET="$HOME/bin/$bin"
    if [[ -L "$TARGET" ]]; then
      rm "$TARGET"          # update existing symlink
    fi
    if [[ -e "$TARGET" ]]; then
      warn "$TARGET already exists and is not a symlink — skipping. Move it aside to use the CLI binaries."
    else
      ln -s "$DIST_DIR/$bin" "$TARGET"
      ok "Linked $TARGET → $DIST_DIR/$bin"
    fi
  done

  # Remind the user to add ~/bin to PATH if it is not already there.
  if ! echo ":${PATH}:" | grep -q ":$HOME/bin:"; then
    warn "~/bin is not in your PATH."
    warn "Add this to your shell profile (~/.zshrc or ~/.bashrc):"
    warn "  export PATH=\"\$HOME/bin:\$PATH\""
    warn "Then run: source ~/.zshrc"
  fi
else
  step "Skipping ~/bin symlinks (NO_SYMLINK=1)"
  ok "Binaries are in $DIST_DIR/"
fi

# ── 6. Summary ────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}Setup complete.${RESET}"
echo ""
echo "  Config : $CONFIG_FILE"
echo "  Daemon : $DIST_DIR/juked"
echo "  TUI    : $DIST_DIR/juke"
echo ""
echo -e "${BOLD}To run (two terminals):${RESET}"
echo ""
echo "  Terminal 1 — start the daemon:"
echo "    juked --foreground"
echo ""
echo "  Terminal 2 — open the TUI:"
echo "    juke"
echo ""
echo "  Or run with full paths if ~/bin is not yet in PATH:"
echo "    $DIST_DIR/juked --foreground"
echo "    $DIST_DIR/juke"
echo ""
echo "  Daemon must be running before the TUI. The daemon prints its socket"
echo "  path to stderr on startup. Config and session files live at:"
echo "    $CONFIG_DIR/"
echo ""
